window.EVENTRIG_SUPPLIERS = [
  {
    name: "Harbour AV Hire",
    city: "Sydney",
    type: "Hire partner",
    price: "from $890",
    categories: ["PA packages", "Wireless mics", "Uplights"],
    fit: ["wedding", "corporate", "party"],
    email: "quotes@example.com",
    website: "https://example.com",
    summary: "Package hire for receptions, speeches and medium rooms.",
  },
  {
    name: "Store DJ",
    city: "Sydney",
    type: "Retail",
    price: "product pricing",
    categories: ["Speakers", "Mixers", "DJ controllers"],
    fit: ["dj", "party", "stage"],
    email: "retail@example.com",
    website: "https://example.com",
    summary: "Retail alternatives for buyers who run events regularly.",
  },
  {
    name: "Wedding Glow Co",
    city: "Sydney",
    type: "Lighting hire",
    price: "quote-ready",
    categories: ["Uplights", "Dance floor", "Warm wash"],
    fit: ["wedding", "party"],
    email: "events@example.com",
    website: "https://example.com",
    summary: "Reception-friendly lighting packages for soft premium rooms.",
  },
  {
    name: "Laneway Production",
    city: "Melbourne",
    type: "Production company",
    price: "from $1,200",
    categories: ["Stage wash", "PA", "Operators"],
    fit: ["corporate", "stage", "dj"],
    email: "melbourne@example.com",
    website: "https://example.com",
    summary: "End-to-end AV for brand launches and small stage shows.",
  },
  {
    name: "Northside Party Hire",
    city: "Brisbane",
    type: "Hire partner",
    price: "from $650",
    categories: ["Party lights", "Subs", "Microphones"],
    fit: ["party", "dj", "wedding"],
    email: "brisbane@example.com",
    website: "https://example.com",
    summary: "Compact sound and lighting packages for private functions.",
  },
  {
    name: "West Coast AV",
    city: "Perth",
    type: "AV company",
    price: "from $980",
    categories: ["Corporate AV", "PA", "Lighting"],
    fit: ["corporate", "stage", "wedding"],
    email: "perth@example.com",
    website: "https://example.com",
    summary: "Reliable conference and presentation AV packages.",
  },
  {
    name: "Festival City Sound",
    city: "Adelaide",
    type: "Audio hire",
    price: "from $720",
    categories: ["PA speakers", "Subwoofers", "Stage monitors"],
    fit: ["stage", "dj", "party"],
    email: "adelaide@example.com",
    website: "https://example.com",
    summary: "Audio-first hire options for performances and dance floors.",
  },
  {
    name: "Capital Event Tech",
    city: "Canberra",
    type: "Production company",
    price: "quote-ready",
    categories: ["Corporate AV", "Wireless mics", "Stage wash"],
    fit: ["corporate", "wedding", "stage"],
    email: "canberra@example.com",
    website: "https://example.com",
    summary: "Formal event AV with microphones, projection and room coverage.",
  },
  {
    name: "Coastline DJ Hire",
    city: "Gold Coast",
    type: "DJ equipment hire",
    price: "from $590",
    categories: ["DJ decks", "Subs", "Moving heads"],
    fit: ["dj", "party"],
    email: "goldcoast@example.com",
    website: "https://example.com",
    summary: "Club-style packages for parties and DJ-led events.",
  },
];
